title: Simonsen
email: Steffentorpe@gmail.com
description: >-
  A blog about things i find interesting
baseurl: ""
url: "https://steffensimonsen.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Show excerpts on homepage
show_excerpts: true


sass:
  sass_dir: assets/css
  style: compressed

# Add custom CSS
plugins:
  - jekyll-feed

# Include custom stylesheets
head_scripts:
  - assets/css/flow-field.css
